### ISSUE TITLE
Drag ends abruptly when dragging an item which is only partially visible

### ISSUE THREAD

**Issue by markini** [Calvin-LL/Reorderable#1]
Here in this video (sample app simple lazy column) I'm trying to drag `Item #7` but get thrown out of the drag after dragging over the next item. This doesn't happen when `Item #7` is fully visible.

Device: Pixel 6a

https://github.com/Calvin-LL/Reorderable/assets/1747400/bf0e9474-fe6b-4e9e-9458-06e159266a99

**Comment by Calvin-LL** [comment]
This is fixed in 1.1.0. It should be available within the hour.
