### ISSUE TITLE
Lag during reorder

### ISSUE THREAD

**Issue by mslalith** [Calvin-LL/Reorderable#15]
The item being dragged seems very laggy and the space for to position is also not being allocated.

Using 1.4.0-beta02

[reorder_lag.webm](https://github.com/Calvin-LL/Reorderable/assets/15076234/2b692cab-cf8c-4e45-acbb-803056a8fb8d)

**Comment by Calvin-LL** [comment]
Can you share your code? I think your `onMove` function in `rememberReorderableLazyColumnState` is moving items into the wrong place. This may be because you have items above the `ReorderableItem`s.

**Comment by mslalith** [comment]
I'm moving at the moment, just trying out the library. Still below is the code I've tried

```kotlin
 val lazyListState = rememberLazyListState()
    val reorderableLazyColumnState = rememberReorderableLazyColumnState(lazyListState = lazyListState) { from, to ->
        println("move: from: $from == to: $to")
    }

Column(
    modifier = modifier
) {
    LazyColumn(
        state = lazyListState,
        verticalArrangement = Arrangement.spacedBy(space = 8.dp),
        modifier = Modifier.padding(horizontal = 12.dp)
    ) {
        items(
            items = list,
            key = { it.id }
        ) { item ->
            ReorderableItem(
                reorderableLazyListState = reorderableLazyColumnState,
                key = item.id
            ) { isDragging ->
                Card(
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        HorizontalSpacer(spacing = 12.dp)
                        Icon(
                            painter = painterResource(id = R.drawable.ic_drag_indicator),
                            contentDescription = null,
                            modifier = Modifier.draggableHandle()
                        )
                        HorizontalSpacer(spacing = 12.dp)
                        Text(
                            text = item.text,
                            modifier = Modifier.padding(vertical = 12.dp)
                        )
                    }
                }
            }
        }
    }
}
```

**Comment by Calvin-LL** [comment]
> I'm not moving at the moment, just trying out the library. Still below is the code I've tried
> 
> ```kotlin
> val lazyListState = rememberLazyListState()
> val reorderableLazyColumnState = rememberReorderableLazyColumnState(lazyListState = lazyListState) { from, to ->
>     println("move: from: $from == to: $to")
> }
> 
> Column(
>     modifier = modifier
> ) {
>     LazyColumn(
>         state = lazyListState,
>         verticalArrangement = Arrangement.spacedBy(space = 8.dp),
>         modifier = Modifier.padding(horizontal = 12.dp)
>     ) {
>         items(
>             items = list,
>             key = { it.id }
>         ) { item ->
>             ReorderableItem(
>                 reorderableLazyListState = reorderableLazyColumnState,
>                 key = item.id
>             ) { isDragging ->
>                 Card(
>                     modifier = Modifier.fillMaxWidth(),
>                 ) {
>                     Row(
>                         verticalAlignment = Alignment.CenterVertically
>                     ) {
>                         HorizontalSpacer(spacing = 12.dp)
>                         Icon(
>                             painter = painterResource(id = R.drawable.ic_drag_indicator),
>                             contentDescription = null,
>                             modifier = Modifier.draggableHandle()
>                         )
>                         HorizontalSpacer(spacing = 12.dp)
>                         Text(
>                             text = item.text,
>                             modifier = Modifier.padding(vertical = 12.dp)
>                         )
>                     }
>                 }
>             }
>         }
>     }
> }
> ```

You will need to modify the `list` in where you have `println("move: from: $from == to: $to")`.

**Comment by mslalith** [comment]
hmm... seems to work after swapping. I thought a state is being maintained internally, so did not swap.
