### ISSUE TITLE
Feature Request: Implement onDragStopped Callback in ReorderableLazyListState

### ISSUE THREAD

**Issue by mak1nt0sh** [Calvin-LL/Reorderable#16]
Hello and thank you for wrapping up everything into a library.

I'd like to suggest an enhancement: integrating the ```onDragStopped {}``` callback directly into the ```ReorderableLazyListState```. Currently, this logic needs to be put within the modifier of every item in a list.

This approach is somewhat cumbersome and can lead to code duplication, particularly in LazyColumn implementations featuring multiple item types, where the logic must be replicated across all item variants.

**Comment by Calvin-LL** [comment]
I can't think of the perfect way to handle if `onDragStopped` is set in both `draggableHandle` and `ReorderableLazyListState`. Should they both run or should only one of them run? If so which one? Any thoughts?

Meanwhile something like this in your code should solve the problem for now:

```kotlin
// ...
@Composable
fun C() {
    val lazyListState = rememberLazyListState()
    val reorderableLazyColumnState = rememberReorderableLazyColumnState(lazyListState) { from, to ->
        // Update the list
    }

    LazyColumn(state = lazyListState) {
        items(list, key = { /* item key */ }) {
            ReorderableItem(reorderableLazyColumnState, key = /* item key */) { isDragging ->
                // Item content

                IconButton(
                    modifier = Modifier
                                .padding(8.dp)
                                .then(
                                    draggableHandle2(
                                        // ...
                                    )
                                ),
                    /* ... */
                )
            }
        }
    }
}
// ...

fun ReorderableItemScope.draggableHandle2(
    enabled: Boolean = true,
    onDragStarted: suspend CoroutineScope.(startedPosition: Offset) -> Unit = {},
    interactionSource: MutableInteractionSource? = null,
) = Modifier.draggableHandle(
    enabled = enabled,
    onDragStarted = onDragStarted,
    onDragStopped = { println("onDragStopped") },
    interactionSource = interactionSource,
)
```

**Comment by mak1nt0sh** [comment]
I think it should be only in ```ReorderableLazyListState```, it's more inline with compose API by not having heavy logic inside ```Modifier```.  You could also pass the last item dropped into index, and from there you can determine the item's type and implement custom logic if needed. Sane for ```onDragStarted```, but anyway, maybe it's what I'm used to as I had my own version of the drag and drop logic.

**Comment by Calvin-LL** [comment]
Consider using `isAnyItemDragging` from #20. You can use a `LaunchedEffect(state.isAnyItemDragging)` to detect drag start and stop.
