### ISSUE TITLE
Updating to Compose Multiplatform 1.6.0

### ISSUE THREAD

**Issue by LOOHP** [Calvin-LL/Reorderable#19]
As Compose Multiplatform [1.6.0-beta02 or below and 1.6.0-rc01 or above is not binary compatible](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-rc01), it stops projects from updating to Compose Multiplatform 1.6.0 if using this library. Would be nice if the beta version of Reordderable could be bumped to Compose Multiplatform 1.6.0.

**Comment by Calvin-LL** [comment]
I have released v1.4.0-beta03 with 1.6.0.
