### ISSUE TITLE
onDrop() lambda?

### ISSUE THREAD

**Issue by dpredovic** [Calvin-LL/Reorderable#21]
Hi!

Very nice work with the library, thanks! :)

Would it be possible to add onDrop() to Reorderable(Lazy)Row/Column and  in addition to onSettle()/onMove() lambda? Or are we supposed to use draggableHandle.onDragStopped()?

**Comment by Calvin-LL** [comment]
just use `onDragStopped`, it should work fine

**Comment by mveroukis** [comment]
True, but onDragStopped doesn't tell you the from/to position of the dragged item.
