### ISSUE TITLE
Moved item snaps back to previous position before continuing to move

### ISSUE THREAD

**Issue by patrickunterwegs** [Calvin-LL/Reorderable#24]
Hi, first of all thank you very much for your great library! :-)

I have an issue that I would like to discuss with you. 
I am using a LazyColumn with ReorderableItems. Source for the list is a room database that is observed as state. Basically the drag and drop works, the items also move to the right position, but before switching places, the dragged item snaps back to its initial position before it continues following the tap: 

https://github.com/Calvin-LL/Reorderable/assets/72232737/7e39d38b-4c9b-49fd-99d9-0a87b19e5c1a

I have seen that 
```
    val reorderableLazyListState = rememberReorderableLazyColumnState(listState) { from, to ->
        val reordered = groupedList.flatMap { it.value }.map { it.iCal4List }.toMutableList().apply {
            add(to.index, removeAt(from.index))
        }
        onUpdateSortOrder(reordered)
    }
```
is called every time an item changes place. It seems like a recomposition happens that makes the dragged item snap back to its previous position before moving on. This might be due to onUpdateSortOrder(...) with the reordered list. Do you maybe have any best practice to avoid this?

One thing I also don't understand is, why the same just works for "ReorderableColumn". 
There is also a difference: While in the reorderableLazyListState the lambda is ALWAYS called when an item changes a place, the onSettle function in ReorderableColumn is only called when dragging was actually finished. 
Is it possible that the handling of the lazy and non lazy variants is a bit different that could cause this issue?

Here's also the whole Composable: https://github.com/TechbeeAT/jtxBoard/blob/32802b75467102cae0292015b0202ec19edb97b8/app/src/main/java/at/techbee/jtx/ui/list/ListScreenCompact.kt

I'd appreciate if you could have a look at this! Thanks a lot :)
- Patrick

**Comment by Calvin-LL** [comment]
Looks like this is related to #4. It will be fixed once https://issuetracker.google.com/issues/209652366 is released.

**Comment by Calvin-LL** [comment]
Try running `onUpdateSortOrder` in a coroutine? It may be taking too long and blocking the [`onDrag`](https://github.com/Calvin-LL/Reorderable/blob/0867a8de5f263fb3a59623ef5cea2c2e587059e5/reorderable/src/commonMain/kotlin/sh/calvin/reorderable/ReorderableLazyList.kt#L408) function in the library.

**Comment by patrickunterwegs** [comment]
Hi @Calvin-LL !
Thanks for looking into it! =)
I have tried it in a Coroutine (actually the underlying code was already executed in a coroutine in the view model anyway). Regrettably it doesn't change anything.

**Comment by patrickunterwegs** [comment]
> One thing I also don't understand is, why the same just works for "ReorderableColumn".
There is also a difference: While in the reorderableLazyListState the lambda is ALWAYS called when an item changes a place, the onSettle function in ReorderableColumn is only called when dragging was actually finished.
Is it possible that the handling of the lazy and non lazy variants is a bit different that could cause this issue?


An addition: the app has lazy columns and Reorderable columns, whereas the Reorderable columns are within the lazy column entries. 
In both cases the same function is called to store the new sort order (as given in the code snippet above). For the Reorderable column this issue doesn't occur, so it's only there for the items within the lazy column...

**Comment by Calvin-LL** [comment]
> > One thing I also don't understand is, why the same just works for "ReorderableColumn".
> There is also a difference: While in the reorderableLazyListState the lambda is ALWAYS called when an item changes a place, the onSettle function in ReorderableColumn is only called when dragging was actually finished.
> Is it possible that the handling of the lazy and non lazy variants is a bit different that could cause this issue?
> 
> 
> An addition: the app has lazy columns and Reorderable columns, whereas the Reorderable columns are within the lazy column entries. 
> In both cases the same function is called to store the new sort order (as given in the code snippet above). For the Reorderable column this issue doesn't occur, so it's only there for the items within the lazy column...

Yeah they're implemented completely separately so I don't think there's much to be gained comparing the two. Is there a branch you're testing this on that I can play with? I tried the branch you had mentioned above on my phone but I can't seem to get any reordering at all.

**Comment by patrickunterwegs** [comment]
Hey @Calvin-LL , thanks!
Sorry, the branch from above was still work in progress. I have set up a branch that now has things finalized and the drag & drop option activated by default: 
https://github.com/TechbeeAT/jtxBoard/tree/1322-feature-order-main-tasksjournalsnotes-by-drag-drop

When you check it out, please make sure you use the OSE build flavor to avoid any restrictions.
I recommend you to use the tasks tab and to switch to the "compact" view through the menu.

**Comment by Calvin-LL** [comment]
Should be fixed in v1.5.2

**Comment by patrickunterwegs** [comment]
Thanks a lot! It looks good now :-)

**Comment by Calvin-LL** [comment]
Sorry to cause more trouble here. This may break again if you update to v2.0.3 or later. Please follow the FAQ in the README to fix it.

**Comment by patrickunterwegs** [comment]
Thank you for the heads-up! I'll check now
