### ISSUE TITLE
`Modifier.animateItemPlacement()` deprecated in Compose Foundation v1.7.0-alpha06

### ISSUE THREAD

**Issue by Calvin-LL** [Calvin-LL/Reorderable#26]
> Item appearance and disappearance animation support was added into LazyColumn and LazyRow. Previously it was possible to add `Modifier.animateItemPlacement()` modifier in order to support placement (reordering) animations. We deprecated this modifier and introduced a new non-experimental modifier called `Modifier.animateItem()` which allows you to support all three animation types: appearance (fade in), disappearance (fade out) and reordering. ([I2d7f7](https://android-review.googlesource.com/#/q/I2d7f7a376cea26c0a36a59a4586d2705ab04cab7), [b/150812265](https://issuetracker.google.com/issues/150812265))

In [Compose Foundation version 1.7.0-alpha06 release notes](https://developer.android.com/jetpack/androidx/releases/compose-foundation).

Should remove `Modifier.animateItemPlacement()` with `Modifier.animateItem()` once v1.7.0 is out.

**Comment by Calvin-LL** [comment]
Did some math in #32 

> Compose Foundation 1.6.0-alpha08 to 1.6.0 took almost 3 months, the latest Compose Multiplatform 1.6.2 uses Compose Foundation 1.6.4 which is a 20-day gap. So expect Compose Foundation v1.7.0 to be in Compose Multiplatform in around 4 months at the current speed.

So that means Compose Foundation v1.7.0 will probably be out around late August - early September.

**Comment by berhram** [comment]
Sorry to bother you. I cloned the lib files into my project. Bumped Compose libs (Android ones because it's an Android app) to 1.7.0-beta02. Replaced animateItemPlacement() with animateItem(), but nothing changed. Did I do something wrong and there is more work to do to adapt to newer Compose versions?

https://github.com/Calvin-LL/Reorderable/assets/68131387/edb427ea-fef2-4a6f-bb77-1077f112ef65

**Comment by Calvin-LL** [comment]
> Sorry to bother you. I cloned the lib files into my project. Bumped Compose libs (Android ones because it's an Android app) to 1.7.0-beta02. Replaced animateItemPlacement() with animateItem(), but nothing changed. Did I do something wrong and there is more work to do to adapt to newer Compose versions?

There are lots of places marked `TODO(foundation v1.7.0)` in the code for 1.7.0 that need to be made before that's fixed.

**Comment by Calvin-LL** [comment]
Good news! v1.7.0 is being released in June according to https://android-developers.googleblog.com/2024/05/whats-new-in-jetpack-compose-at-io-24.html, we should see v1.7.0 land in Compose Multiplatform some time in June/July.

**Comment by westnordost** [comment]
Looks like they have been late. But it has been released now on the 4th of September.

**Comment by Calvin-LL** [comment]
Unfortunately I still have to wait until it hits [multiplatform](https://github.com/JetBrains/compose-multiplatform/releases). The good news is you can use the beta version of this library, it uses the beta version of multiplatform which has 1.7.0.

**Comment by Calvin-LL** [comment]
Amazing! I'll update asap

**Comment by Calvin-LL** [comment]
[v2.4.0](https://github.com/Calvin-LL/Reorderable/releases/tag/v2.4.0) is out

**Comment by aryanhaque017** [comment]
Can I use animateItem() for production apps?

**Comment by Calvin-LL** [comment]
> Can I use animateItem() for production apps?

it's not experimental anymore I don't think
