### ISSUE TITLE
feature request: support grid reordering

### ISSUE THREAD

**Issue by ycmjason** [Calvin-LL/Reorderable#28]
Thank you so much for making such great library.

It would be absolutely amazing if this library can support grid reordering too. I am putting this feature request in in case we forget 😄.

❤️

**Comment by Calvin-LL** [comment]
I'll look into that next week. Should be doable for `LazyGrid`s.

**Comment by ycmjason** [comment]
You are absolutely the best! Honestly, tried a couple of libraries your api is the most intuitive so far!

**Comment by Waboodoo** [comment]
I would also be interested in `LazyGrid` support. I've been using https://github.com/aclassen/ComposeReorderable for this so far, but that doesn't seem to be maintained anymore, so it would be great if I could fully migrate away from it to your library.

**Comment by Calvin-LL** [comment]
I have good news! I got it to work with grids. I'll try to release it this week.

**Comment by Calvin-LL** [comment]
Released in v2.0.0

**Comment by ycmjason** [comment]
Let's gooooo 💯💯
