### ISSUE TITLE
Please add "detectReorderAfterLongPress" modifier 

### ISSUE THREAD

**Issue by Monabr** [Calvin-LL/Reorderable#3]
Hi. Please add `detectReorderAfterLongPress` so I would not need to have element with I need to use to drag but have whole item available for drag once it's long pressed.

**Comment by Calvin-LL** [comment]
I've added `Modifier.longPressDraggableHandle` in 1.2.0. If you want to be able to drag the whole item, just apply the modifier to the whole item.
