### ISSUE TITLE
ReorderableLazyRow doesn't work on version 2.0

### ISSUE THREAD

**Issue by wesjon** [Calvin-LL/Reorderable#30]
Using the official example "Simple Reorderable LazyRow" is not working since the update 2.0

**Current behavior:**
When user reorders an item in LazyRow the item returns to its original position

https://github.com/Calvin-LL/Reorderable/assets/2665419/2b44810d-1daf-404f-9957-31889962fff8

**Expected behavior:**
The item should move the the new position.

**Comment by Calvin-LL** [comment]
Oops didn't notice that. I will take a look. Thanks for letting me know!

**Comment by Calvin-LL** [comment]
This is very strange. What device and android version is this?

**Comment by Calvin-LL** [comment]
Does ReorderableColumn work for you?

**Comment by wesjon** [comment]
@Calvin-LL Yes, all Column layouts work. ReoderableRow also works but the ReorderableLazyRow shows the behavior shown in the video. I tested on a Galaxy S23 Ultra running Android 14.

**Comment by Calvin-LL** [comment]
Should be fixed in v2.0.1

**Comment by wesjon** [comment]
Thanks @Calvin-LL 
Just tested again and it's working perfectly now.
