### ISSUE TITLE
Reordering Rows in RTL doesn't work in versions 1.5.2 and 2.0

### ISSUE THREAD

**Issue by wesjon** [Calvin-LL/Reorderable#31]
**Current behavior:**
When the user's device is set to a RTL language (or Force RTL direction on developer's settings) ordering rows doesn't work. This behavior was confirmed in versions 1.5.2 and 2.0

Example **_ReorderableRow_** from the official demo:

https://github.com/Calvin-LL/Reorderable/assets/2665419/e0aa87c7-2561-4ad3-ab99-4c20480cf954

**Expected behavior:**
Rows should reorderable regardless of layout direction (LTR or RTL)

**Comment by Calvin-LL** [comment]
Thank you so much for finding these!!!

**Comment by wesjon** [comment]
You're welcome! Your library is awesome!

**Comment by Calvin-LL** [comment]
Should be fixed in v2.0.1

**Comment by wesjon** [comment]
Thanks @Calvin-LL 
Just tested again and it's working perfectly now.
