### ISSUE TITLE
How can I implement PagingData with reorderable using this?

### ISSUE THREAD

**Issue by idineshgovind** [Calvin-LL/Reorderable#33]
I can able to implement this library for list, but i need to do it for PagingData as well, please help on this

i get the items as  `"LazyPagingItems<Modal>"`

**Comment by Calvin-LL** [comment]
I'm not sure how `PagingData` works. Do you have an example for the problem you're running into?

**Comment by idineshgovind** [comment]
This is a snippet from my viewmodel where I get the data as flow from DB:

   ```
fun getNotebooks(): Flow<PagingData<ZNotebook>> {
        val pager = Pager(
            config = PagingConfig(pageSize = FETCH_LIMIT_FROM_LOCAL_DB, enablePlaceholders = false),
            pagingSourceFactory = { BooksPagingSource(useCase) }
        )
        return pager.flow.cachedIn(viewModelScope)
    }
```

this is how I can call this in UI for further uses
`val notebooks : LazyPagingItems<ZNotebook> = notebookViewmodel.getNotebooks().collectAsLazyPagingItems()`

by using your library we can able to load the mutable list and can able to reorder that. but here i can load this in items, but reorder does not work. because in your library we need to add the data to list first and then only we have to load.

I also found a workaround to do that also
```
notebooks.itemSnapshotList.forEach { notebook ->
                if (!notebooksList.value.contains(notebook!!)) {
                    notebooksList.value += notebook
                }
            }
```

but flow doesn't work here, if any value updated in DB, its not reflecting here. please help me

**Comment by Calvin-LL** [comment]
At the end of `rememberReorderableLazyListState` there is a function called `onMove`, it tells you which item on the list is moved to. In there you should update your database, then the items in the list will move accordingly. Is there a part of that you can't figure out?

**Comment by Calvin-LL** [comment]
Oh I think you may need to come up with a way to store the reordering kind of like here: https://stackoverflow.com/questions/77493363/how-to-remove-update-an-item-from-flowpagingdata-in-jetpack-compose
