### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by idineshgovind** [Calvin-LL/Reorderable#35]
Is it possible to handle a case where a user starts dragging an item, doesn't move it, and then drops it in the same position?.

onMove didn't triggered when dropped on a same position of dragged item

**Comment by idineshgovind** [comment]
I think giving item index on onDragStarted and onDragEnded will be solve this, 
I think offset only available on onDragStarted

**Comment by Calvin-LL** [comment]
You can just use the index in the `itemsIndexed` scope by replacing your `items` with `itemsIndexed`. Neither `onDragStarted` or `onDragStopped` provide the item index.

**Comment by idineshgovind** [comment]
I am not sure how is it possible using itemIndexed, any sample codes please? 

```
.longPressDraggableHandle(
                                    isReorderAllowed.value,
                                    onDragStarted = {
                                        dragStartIndex = index
                                    },
                                    onDragStopped = {
                                        dragEndIndex = index

                                        if (dragStartIndex == dragEndIndex) {
                                            Toast.makeText(mContext, "Item was not moved", Toast.LENGTH_SHORT).show()
                                        }

                                    })
```


This condition is always true even though if I dragged to another index

**Comment by Calvin-LL** [comment]
`dragStartIndex` is a `remember { mutableState() }` right? And for the end index try just checking the index without having a variable.

**Comment by Calvin-LL** [comment]
And try printing the index at both places to see if they look right.

**Comment by Calvin-LL** [comment]
Oh wait nevermind I think they should always be the same. Try adding a variable called `isMoved` or something, set it to false when drag starts, set it to true in onMove, check it when drag stops.

**Comment by idineshgovind** [comment]
Tried printing both, getting same index value on both(index where the drag satrted)

**Comment by idineshgovind** [comment]
Worked, Thanks :)
