### ISSUE TITLE
Question: How if I want to receive click and long clock event for child composables of ReorderableItem  

### ISSUE THREAD

**Issue by neronguyenvn** [Calvin-LL/Reorderable#36]
Thanks for your helping. Is it related to MutableInteractionSource ?. I can add 1 more pointerInput into longPressDraggable but it not smart, not customizable.

**Comment by Calvin-LL** [comment]
Hmm. Not sure exactly what you mean here. Do you want an item to start dragging both when the handle is clicked and long clicked?

**Comment by neronguyenvn** [comment]
I mean if I set longPressDraggable for a modifier of a item, I can't set combine clickable for it to handle long press event.

**Comment by Calvin-LL** [comment]
Why not use `onDragStarted`?
