### ISSUE TITLE
[Q] Why column does not support dragging to the edge?

### ISSUE THREAD

**Issue by shimika** [Calvin-LL/Reorderable#37]
Scrolls when dragging to the edge of the screen. (unavailable for [Column](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#Column(androidx.compose.ui.Modifier,androidx.compose.foundation.layout.Arrangement.Vertical,androidx.compose.ui.Alignment.Horizontal,kotlin.Function1)) and [Row](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#Row(androidx.compose.ui.Modifier,androidx.compose.foundation.layout.Arrangement.Horizontal,androidx.compose.ui.Alignment.Vertical,kotlin.Function1))) The scroll speed is based on the distance from the edge of the screen.

I use Column to my app because Item has TextField and LazyColumn has issue about focusing TextField

**Comment by Calvin-LL** [comment]
Can you share a screen recording of this happening?
