### ISSUE TITLE
Please support the ability to disable the item animations

### ISSUE THREAD

**Issue by ibcurly** [Calvin-LL/Reorderable#40]
I would like the ability to disable the animations caused by animateItemPlacement for the entire list.
In my implementation, users have the ability to enable/disable "drag mode" and I need the animateItemPlacement animations to disable when "drag mode" is off in order for other item animations to work properly.

The enabled boolean inside "ReorderableItem" can toggle the drag behavior, but the item placement animation still remains.

Currently, my workaround is to choose between a ReorderableItem (which forces the item placement animation) and a regular item, but this makes the transition between the two states a bit janky since the entire list is recomposed. 

`
if (isDragMode) {
        ReorderableItem(...) { ItemContent() }
} else {
        ItemContent()
}
`

Any ideas? 
Thank you so much!

**Comment by Calvin-LL** [comment]
I will look into it. Been meaning to add that when foundation 1.7.0 comes out.

**Comment by Calvin-LL** [comment]
Try v2.2.0, you should be able to do
```kotlin
ReorderableItem(
    // ...
    animateItemModifier = if (isDragMode) { Modifier.animateItemPlacement() } else { Modifier }
)
```

**Comment by ibcurly** [comment]
That was fast, worked like a charm! Thank you

**Comment by ibcurly** [comment]
To anyone else who finds this,
For my particular case of trying to get the item placement animation to play well with other existing item animations like expand/collapse: dynamically adjusting the animation specs inside of the item placement modifier instead of enabling/disabling the animation modifier itself yielded better results.
(which this recent update also enables you to do)
