### ISSUE TITLE
Dragging Across Multiple Lists

### ISSUE THREAD

**Issue by jimbroze** [Calvin-LL/Reorderable#41]
Is it currently possible to drag & drop between different levels of nested lists? That is; if I have a list within another list, is it possible to drag an item from the parent list into the child list and vice versa? If not, how much work would it take to achieve this?

Taking this concept even more abstract, would it be possible to drag and drop between completely separate lists?

**Comment by Calvin-LL** [comment]
No. Dragging between lists is not possible. But instead of nesting lists, why not just make the nested items smaller to create the look of a nested list?
