### ISSUE TITLE
Problem in the case of a lazy column with 3 large items

### ISSUE THREAD

**Issue by mharam** [Calvin-LL/Reorderable#51]
Hi,

Thank you for this useful library. I encountered a problem with this library. When I have 3 items with large height in the `LazyColumn`  that the third item lies partially outside the column height, then if I try to drag item #1 to place at item #0 the `LazyColumn` scrolls and I cannot complete the reordering process.
In order to reproduce this condition change the `items` variable as follows:
```
val items = (0..2).map {
    Item(id = it, text = "Item #$it", size = if (it % 2 == 0) 270 else 400)
}
```
Then compile it on an 6'' phone emulator like Pixel 6a.

With regards

**Comment by Calvin-LL** [comment]
Can you provide a screen recording?

**Comment by Calvin-LL** [comment]
Might be related to https://github.com/Calvin-LL/Reorderable/issues/4#issuecomment-2107410640 and https://github.com/Calvin-LL/Reorderable/issues/46

**Comment by mharam** [comment]
[Screen_recording_20240916_112540.webm](https://github.com/user-attachments/assets/7dc7aaef-b6a5-4b0c-bddf-f7543d4cca05)

I'm not sure it's exactly related to the issues you mentioned. But it may be related to some extent.

**Comment by Calvin-LL** [comment]
Looks like it's related to #4, it should still work if you drag it all the way up. Give [v2.4.0-beta01](https://github.com/Calvin-LL/Reorderable/releases/tag/v2.4.0-beta01) a try, it has Compose Foundation v1.7.0 so it should work.

**Comment by mharam** [comment]
Android studio gives error:
Failed to resolve: sh.calvin.reorderable:reorderable:v2.4.0-beta01
Chrome also gives 404 Not Found error!

**Comment by Calvin-LL** [comment]
Very strange. I did publish it https://central.sonatype.com/artifact/sh.calvin.reorderable/reorderable/versions

**Comment by Calvin-LL** [comment]
Oh it should be `sh.calvin.reorderable:reorderable:2.4.0-beta01` without the "v"

**Comment by mharam** [comment]
Thank you so much. It now works perfectly!
