### ISSUE TITLE
Should `isDragging` for ReorderableItem be true when item settles?

### ISSUE THREAD

**Issue by westnordost** [Calvin-LL/Reorderable#52]
In Material design, the dragged item is usually shown with a certain elevation to denote that it is kind of floating above the list while dragged.

When one drops the reorderable item, there is a snap-in-place animation where the reordered item settles back into the list.

I noticed that during this animation, `isDragging` is already false, resulting in the item not being displayed as "floating above" anymore.

To me this looks odd, because as long as the reordered item is not fully settled back into the list after dragging, it partly overlaps other items and thus should appear visually above them.

**Comment by Calvin-LL** [comment]
I have that because I wanted the item to lower on its way to the final position as oppose to translating to above the final position then lower itself. I've tried both and the former seems nicer, it feels faster and more what one would expect where the item flys to its final position in 3D.

**Comment by westnordost** [comment]
No, I don't feel strongly about it. I haven't actually tried how it would look like if it would only lower itself when in place, but you have, so that's nice.
