### ISSUE TITLE
Move or reorder items with animation programatically

### ISSUE THREAD

**Issue by mianaliasjad** [Calvin-LL/Reorderable#53]
I wanna achieve such behavior that it moves the item from one index to another without user interaction, i simply provide two indexes where I tell i wanna move the item from this index to the destination index.

Does that function already exist? if not it will be a great edition.

**Comment by Calvin-LL** [comment]
In a LazyColumn or LazyRow, you can do that by adding `Modifier.animateItem()` to all items in the list. Then change the items' order.
