### ISSUE TITLE
Dragging problem

### ISSUE THREAD

**Issue by mahramane** [Calvin-LL/Reorderable#61]
Hello
I copied and executed the sample code exactly on the first page of GitHub but I encountered this problem.
When I drag an item up or down, it shakes like this and doesn't move.

https://github.com/user-attachments/assets/21f4bed1-3ee4-4ac1-9912-488d1a0a5721

**Comment by iguerendiain** [comment]
What was the issue? I'm having the same problem.

**Comment by Calvin-LL** [comment]
I think the indexes that were being swapped were incorrect @iguerendiain

**Comment by iguerendiain** [comment]
Actually, just a few minutes ago I found that the issue was exactly that (was specifying the wrong key to ReorderableItem in my case) and forgot to came back here and answer myself. Thanks @Calvin-LL , amazing library by the way.
