### ISSUE TITLE
Wrongly package macos skiko dylib for android target on 1.3.0

### ISSUE THREAD

**Issue by VDostoyevskiy** [Calvin-LL/Reorderable#8]
https://github.com/FooIbar/EhViewer/actions/runs/7791277736

**Comment by Calvin-LL** [comment]
I can't see the error in the actions run. Can you point me to it?

**Comment by VDostoyevskiy** [comment]
> I can't see the error in the actions run. Can you point me to it?

The artifacts bloated much compared to its parent
Extract the apk, and you will find macos dylib

**Comment by Calvin-LL** [comment]
Fixed in 1.3.1. Thank you for alerting me to the issue!

**Comment by Calvin-LL** [comment]
Please reopen this if it's not fixed in 1.3.1. I tried it locally and it seems to work.
